sudo: required
dist: trusty
language: node_js
node_js:
- "10"
install:
- npm install -g truffle ganache-cli eth-gas-reporter
- npm install
script:
  - ganache-cli -p 8545 > /dev/null &
  - sleep 5
  - truffle test
  - truffle run coverage
